//
//  MainProtocols.swift
//  B2SDemo
//
//  Created Egor Sakhabaev on 09.07.2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import Foundation

// MARK: - Wireframe
enum MainNavigationOption {
//    case firstModule
//    case secondModule(someData)
}

protocol MainWireframeInterface: AnyObject {
    func navigate(to option: MainNavigationOption)
}

// MARK: - Presenter
protocol MainPresenterInterface: AnyObject {
    
    var interactor: MainInteractorInput? { get set }
    
    func didRequestPurchaseProduct(name: String)
    
    // MARK: - Lifecycle
    func viewDidLoad()
    func viewWillAppear()
    func viewDidAppear()
    func viewWillDisappear()
    func viewDidDisappear()
}

extension MainPresenterInterface {
    func viewDidLoad() {/*leaves this empty*/}
    func viewWillAppear() {/*leaves this empty*/}
    func viewDidAppear() {/*leaves this empty*/}
    func viewWillDisappear() {/*leaves this empty*/}
    func viewDidDisappear() {/*leaves this empty*/}
}

// MARK: - Interactor
protocol MainInteractorOutput: AnyObject {

    func fetchedCurrentPurchaseStatus(with data: (productId: String, isActive: Bool, expDate: Date?))
    func fetchedCurrentPurchaseStatus(with errorData: (productId: String, error: Error))

    func purchasedProduct()
    func purchasedProduct(with error: Error)
    
    func fetchedFully()
    /* Interactor -> Presenter */
}

protocol MainInteractorInput: AnyObject {
    
    var presenter: MainInteractorOutput? { get set }

    func fetchCurrentPurchaseStatus()
    func purchaseProduct(id: String)
    /* Presenter -> Interactor */
}

// MARK: - View
protocol MainView: AnyObject {
    
    var presenter: MainPresenterInterface? { get set }

    func displayActive(productId: String,
                       expDate: String)
    func resetSubscriptionsStates()

    func startLoading()
    func stopLoading()
    /* Presenter -> ViewController */
}
