//
//  MainConfigurator.swift
//  B2SDemo
//
//  Created Egor Sakhabaev on 09.07.2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

struct MainConfigurator {
    
    static func createModule() -> UIViewController {
        let storyboard = UIStoryboard(name: "Main", bundle: Bundle.main)
        guard let storyboardViewController = storyboard.instantiateInitialViewController() else {
            fatalError("Main.storyboard has no initial view controller")
        }
        
        let viewController: UIViewController?
        if storyboardViewController is UINavigationController {
            viewController = (storyboardViewController as? UINavigationController)?.viewControllers.first
        } else {
            viewController = storyboardViewController
        }
        
        guard let view = viewController as? MainViewController else {
            fatalError("Failed to cast to MainViewController")
        }
        
        let interactor = MainInteractor()
        let router = MainRouter()
        let presenter = MainPresenter(interface: view,
                                      interactor: interactor,
                                      router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return storyboardViewController
    }
}
