//
//  MainInteractor.swift
//  B2SDemo
//
//  Created Egor Sakhabaev on 09.07.2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import Foundation
import SwiftyStoreKit
import StoreKit

final class MainInteractor: MainInteractorInput {
    
    // MARK: - Properties
    weak var presenter: MainInteractorOutput?
    
    // MARK: - MainInteractorInput
    func purchaseProduct(id: String) {
        SwiftyStoreKit.purchaseProduct(id, quantity: 1, atomically: true) { [weak self] result in
            switch result {
            case .success(let product):
                self?.presenter?.fetchedFully()
                self?.presenter?.purchasedProduct()
                print("Purchased Success: \(product.productId)")
            case .error(let error):
                self?.presenter?.fetchedFully()
                self?.presenter?.purchasedProduct(with: error)
            }
        }
    }
}
