//
//  MainRouter.swift
//  B2SDemo
//
//  Created Egor Sakhabaev on 09.07.2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

final class MainRouter {
    
    // MARK: - Properties
    weak var viewController: UIViewController?
}

// MARK: - MainWireframeInterface
extension MainRouter: MainWireframeInterface {
    
    func navigate(to option: MainNavigationOption) {
//        switch option {
//        case .firstModule:
//            openFirstModule()
//        case .secondModule(let someData):
//            openSecondModule(with someData)
//        }
    }
}
