//
//  MainViewController.swift
//  B2SDemo
//
//  Created Egor Sakhabaev on 09.07.2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit
import B2S

class MainViewController: UIViewController {
    // MARK: - Properties
	var presenter: MainPresenterInterface?

    // MARK: - IBOutlets
    @IBOutlet weak var loaderView: UIView!
    @IBOutlet weak var activityIndicatorView: UIActivityIndicatorView!

    // MARK: - Lifecycle -
	override func viewDidLoad() {
        super.viewDidLoad()
        configureUI()
        presenter?.viewDidLoad()
    }
}

// MARK: - UI Configuration
extension MainViewController {
    private func configureUI() {
    }
}

// MARK: - MainView
extension MainViewController: MainView {
    func startLoading() {
        UIView.animate(withDuration: 0.25) {
            self.loaderView.alpha = 1.0
            self.activityIndicatorView.startAnimating()
        }
    }
    
    func stopLoading() {
        UIView.animate(withDuration: 0.25) {
            self.loaderView.alpha = 0.0
            self.activityIndicatorView.stopAnimating()
        }
    }
}

// MARK: - Actions
extension MainViewController {
    @IBAction
    func purchaseDidSelect(_ sender: UIButton) {
        presenter?.didRequestPurchaseProduct(name: "com.b2s.subscription.oneMonth")
    }
    
    @IBAction
    func openPromoDidSelect() {
    }
}

