//
//  MainPresenter.swift
//  B2SDemo
//
//  Created Egor Sakhabaev on 09.07.2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import Foundation
import B2S
import StoreKit

final class MainPresenter {
    
    // MARK: - Properties
    weak private var view: MainView?
    var interactor: MainInteractorInput?
    private let router: MainWireframeInterface
    
    // MARK: - Initialization and deinitialization
    init(interface: MainView,
         interactor: MainInteractorInput?,
         router: MainWireframeInterface) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

// MARK: - MainPresenterInterface
extension MainPresenter: MainPresenterInterface {
    func didRequestPurchaseProduct(name: String) {
        view?.startLoading()
        interactor?.purchaseProduct(id: name)
    }
    
    // MARK: - Lifecycle -
    func viewDidLoad() {
        B2S.shared.delegate = self
    }
}

// MARK: - MainInteractorOutput
extension MainPresenter: MainInteractorOutput {
    func purchasedProduct() {
        
    }
    
    func purchasedProduct(with error: Error) {
        
    }
    
    func fetchedFully() {
        view?.stopLoading()
    }
}

// MARK: - B2SDelegate
extension MainPresenter: B2SDelegate {
    func b2sPromotionOfferDidPurchase(productId: String, offerId: String, transaction: SKPaymentTransaction) {
        // Deliver content from server, aaply subscription and then call: SKPaymentQueue.default().finishTransaction(transaction) unless you do it elsewhere
    }
}

