//
//  FirstOfferRouter.swift
//  B2S
//
//  Created Egor Sakhabaev on 05.07.2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

final class FirstOfferRouter {
    
    // MARK: - Properties
    weak var viewController: UIViewController?
}

// MARK: - FirstOfferWireframeInterface
extension FirstOfferRouter: FirstOfferWireframeInterface {
    
    func navigate(to option: FirstOfferNavigationOption) {
        switch option {
        case .dismiss:
            viewController?.dismiss(animated: true)
        }
    }
}
