//
//  FirstOfferInteractor.swift
//  B2S
//
//  Created Egor Sakhabaev on 05.07.2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import Foundation

final class FirstOfferInteractor: FirstOfferInteractorInput {
    
    // MARK: - Properties
    weak var presenter: FirstOfferInteractorOutput?
    
    // MARK: - FirstOfferInteractorInput
}
