//
//  FirstOfferViewController.swift
//  B2S
//
//  Created Egor Sakhabaev on 05.07.2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

class FirstOfferViewController: UIViewController {
    // MARK: - Properties
	var presenter: FirstOfferPresenterInterface?

    // MARK: - Lifecycle -
	override func viewDidLoad() {
        super.viewDidLoad()
        configureUI()
        presenter?.viewDidLoad()
    }
}

// MARK: - UI Configuration
extension FirstOfferViewController {
    private func configureUI() {
        
    }
}

// MARK: - FirstOfferView
extension FirstOfferViewController: FirstOfferView {
    
}
