//
//  FirstOfferProtocols.swift
//  B2S
//
//  Created Egor Sakhabaev on 05.07.2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import Foundation

// MARK: - Wireframe
enum FirstOfferNavigationOption {
//    case firstModule
//    case secondModule(someData)
}

protocol FirstOfferWireframeInterface: AnyObject {
    func navigate(to option: FirstOfferNavigationOption)
}

// MARK: - Presenter
protocol FirstOfferPresenterInterface: AnyObject {
    
    var interactor: FirstOfferInteractorInput? { get set }
    
    // MARK: - Lifecycle
    func viewDidLoad()
    func viewWillAppear()
    func viewDidAppear()
    func viewWillDisappear()
    func viewDidDisappear()
}

extension FirstOfferPresenterInterface {
    func viewDidLoad() {/*leaves this empty*/}
    func viewWillAppear() {/*leaves this empty*/}
    func viewDidAppear() {/*leaves this empty*/}
    func viewWillDisappear() {/*leaves this empty*/}
    func viewDidDisappear() {/*leaves this empty*/}
}

// MARK: - Interactor
protocol FirstOfferInteractorOutput: AnyObject {
    
    /* Interactor -> Presenter */
}

protocol FirstOfferInteractorInput: AnyObject {
    
    var presenter: FirstOfferInteractorOutput? { get set }
    
    /* Presenter -> Interactor */
}

// MARK: - View
protocol FirstOfferView: AnyObject {
    
    var presenter: FirstOfferPresenterInterface? { get set }
    
    /* Presenter -> ViewController */
}
