//
//  FirstOfferProtocols.swift
//  B2S
//
//  Created Egor Sakhabaev on 05.07.2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import Foundation
import StoreKit

// MARK: - Wireframe
enum FirstOfferNavigationOption {
    case dismiss
}

protocol FirstOfferWireframeInterface: AnyObject {
    func navigate(to option: FirstOfferNavigationOption)
}

// MARK: - Presenter
protocol FirstOfferPresenterInterface: AnyObject {
    
    var interactor: FirstOfferInteractorInput? { get set }
    
    func didSelectAction()
    func didSelectClose()
    
    // MARK: - Lifecycle
    func viewDidLoad()
    func viewWillAppear()
    func viewDidAppear()
    func viewWillDisappear()
    func viewDidDisappear()
}

extension FirstOfferPresenterInterface {
    func viewDidLoad() {/*leaves this empty*/}
    func viewWillAppear() {/*leaves this empty*/}
    func viewDidAppear() {/*leaves this empty*/}
    func viewWillDisappear() {/*leaves this empty*/}
    func viewDidDisappear() {/*leaves this empty*/}
}

// MARK: - Interactor
protocol FirstOfferInteractorOutput: AnyObject {
    
    func purchasedPromotionOffer(with transaction: SKPaymentTransaction, offerData: (productId: String, offerId: String))
    func purchasedPromotionOffer(with error: Error, offerData: (productId: String, offerId: String))

    func fetchedFully()
    /* Interactor -> Presenter */
}

protocol FirstOfferInteractorInput: AnyObject {
    
    var presenter: FirstOfferInteractorOutput? { get set }
    
    func purchasePromotionOffer(productId: String, offerId: String)
    /* Presenter -> Interactor */
}

// MARK: - View
protocol FirstOfferView: AnyObject {
    
    var presenter: FirstOfferPresenterInterface? { get set }
    
    func display(image: ImageData?,
                 title: TextData?,
                 subtitle: TextData?,
                 footer: String?,
                 offer: TextData?,
                 promotionButton: ButtonData,
                 background: (image: ImageData?,
                              color: String?))
    
    func startLoading()
    func stopLoading()
    /* Presenter -> ViewController */
}
